recipe: resources depending on authenticated user
octo-woapi/cookbook pull request #22
Opened 2021-05-21 12:18 UTC by mathieulemorvan

2021-06-07 10:17 UTC, kevin-julien reviewed
La recette est bien !

2021-06-07 10:17 UTC, kevin-julien commented on recipes/resources-depending-on-authenticated-user.md
> +I expect my API to be used by a frontend, with a user already authenticated (generally by an OAuth2 access token).
Le use-case s'applique également à n'importe quel type de client (CLI, backend).

2021-06-07 10:17 UTC, kevin-julien commented on recipes/resources-depending-on-authenticated-user.md
> +Having these limits in mind, what can we do?\
Il y a un antislash qui reste à la fin de la ligne

2021-06-07 10:17 UTC, kevin-julien commented on recipes/resources-depending-on-authenticated-user.md
> +This implies a slight constraint for the API Client: extract the user id from the access token (generally in the `sub` claim). But in most context, user id should be an information already known by t
Cela implique également que le backend vérifie le type d'utilisateur et s'il est autorisé à visualiser les données d'un autre utilisateur.

2021-06-07 10:17 UTC, kevin-julien commented on recipes/resources-depending-on-authenticated-user.md
> +- `GET /profile/@me`
Comme pour les exemples précédents, j'aurai bien mis un petit cURL

2021-07-02 07:26 UTC, mathieulemorvan commented on recipes/resources-depending-on-authenticated-user.md
> +I expect my API to be used by a frontend, with a user already authenticated (generally by an OAuth2 access token).
j'ai reformulé !

2021-07-02 07:39 UTC, mathieulemorvan commented on recipes/resources-depending-on-authenticated-user.md
> +This implies a slight constraint for the API Client: extract the user id from the access token (generally in the `sub` claim). But in most context, user id should be an information already known by t
bien vu, je rajoute la contrainte

2021-07-02 08:05 UTC, Floby commented on recipes/resources-depending-on-authenticated-user.md
> +Let's start with a _don't_: use the access token as a "parameter" of a regular endpoint is not a good idea.
```suggestion
Let's start with a _don't_

> using the access token as a implicit parameter of a regular endpoint is not a good idea.
```

2021-07-02 08:05 UTC, Floby commented on recipes/resources-depending-on-authenticated-user.md
> +Let's start with a _don't_: use the access token as a "parameter" of a regular endpoint is not a good idea.
je pense que le mot-clé _implicite_ est important pour raccrocher à des éléments connus de code smell.

2021-07-02 11:59 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +Let's start with a _don't_: use the access token as a "parameter" of a regular endpoint is not a good idea.
a implicit -> an implicit

2021-07-02 12:15 UTC, simonrenoult reviewed
Quelques retours de forme, looks good sur le fond :+1:

2021-07-02 12:15 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +I expect my API to be called with an already authenticated user  (generally by an OAuth2 access token). This happens when the Client is a frontend, even if my API could also be used for server-to-ser
```suggestion
I expect my API to be called with an already authenticated user (usually by an OAuth2 access token). This happens when the Client is a frontend or any other backend service.
```

2021-07-02 12:15 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +- list of user orders...
```suggestion
- list of user orders
- etc.
```

2021-07-02 12:15 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +How can I do that?\
```suggestion
How can I do that?
```

2021-07-02 12:15 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +The backend just extracts the user id from the access token, and use it as the parameter of the endpoint:
```suggestion
The backend will extract the user id from the access token, and use it as the parameter of the endpoint:
```

2021-07-02 12:15 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +With an access token belonging to Alice:
```suggestion
Given an access token belonging to Alice:
```

2021-07-02 12:15 UTC, simonrenoult commented on recipes/resources-depending-on-authenticated-user.md
> +Seems pretty convenient, no? But what's wrong with this design?
```suggestion
Seems pretty convenient, right? But what's wrong with this design?
```

2021-07-02 13:18 UTC, KCH-KENG requested changes

2021-07-02 13:18 UTC, KCH-KENG commented on recipes/resources-depending-on-authenticated-user.md
> +I expect my API to be called with an already authenticated user  (generally by an OAuth2 access token). This happens when the Client is a frontend, even if my API could also be used for server-to-ser
```suggestion
I expect my API to be called with an authenticated user (generally by an OAuth2 access token). This happens when the Client is a frontend, even if my API could also be used for server-to-server calls.
```

2021-07-08 15:57 UTC, merged