Feat: documentation auto génerée
octo-woapi/cookbook pull request #51
Opened 2021-08-06 14:16 UTC by SamiTlili

2021-09-17 11:17 UTC, mathieulemorvan requested changes

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +## Recipe
j'ai l'impression que toute la première partie c'est plutôt "pourquoi documenter une API"
et la partie vraiment "recette" c'est le "How to ?"

je te suggère donc de faire juste ces deux parties, et d'alléger la partie "why" car ce n'est pas un article de fond mais une recette

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +- Allows to describe request body.
virer certains points qui tombent sous le sens (les 4 derniers)

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +### Facilitate the integration of an API
pour ta partie "why" je virerais toutes les sous-parties, histoire d'être plus direct

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +This documentation contains instructions about how to effectively use and integrate with an API.\
déjà dit

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +- Automate the generation of your documentation.
en fait j'inverserais cette partie avec "Swagger as example :", et je mettrais ça dans "Recipe"

ce qui donnerait un truc du genre :

We highly recommend you to choose OpenAPI standards. It's a most used standard for API documentation.\
The OpenAPI specification was known as Swagger until version 3.0.\
<ajouter un mot pour dire que Swagger UI permet d'afficher une doc OpenAPI, mais qu'il en existe d'autres genre Redoc>
An example can be found here: [Petstore sample](https://petstore.swagger.io/) provided by [swagger.io](https://swagger.io/) team. 

Example of an OpenAPI file in yaml format:

```yaml
  paths: ...
```

puis les exemples de code

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +- You can document your APIs errors.
je pense que tous ces bullets sont redondants, on a compris que ça sert à documenter

straight to the point: "implementation example with Node.Js" /  "implementation example with Java"

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +### Facilitate the integration of an API
et il manque un petit truc dans le Why : insister sur l'intérêt de la génération automatique de la doc (ne pas se repalucher chaque changement à la main dans un yaml)

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +For more information on error documentation : [API Error format](https://octo-woapi.github.io/cookbook/error-format.html).
bien vu ! doit y avoir moyen de faire un lien relatif non ?

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +#### Documentation
top d'avoir mis ça
je pense que tu peux le laisser en titre de 2e niveau

2021-09-17 11:17 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +
pour la partie java :

### Implementation example in Java / Kotlin / Spring

If you have a Spring application (in Java or Kotlin), you can use the [Springfox lib](https://springfox.github.io/springfox/) to:
- generate automatically an OpenAPI description of the endpoints declared in your application (json or yaml file)
- expose a Swagger UI static page on your application, displaying the generated documentation

Add Springfox dependency, for example with Gradle and SpringBoot:
```kotlin
dependencies {
    implementation "io.springfox:springfox-boot-starter:3.0.0"
}
```

Declare the API in a dedicated config file, using the `@EnableSwagger2` annotation:
```kotlin
@Configuration
@EnableSwagger2
class SwaggerConfig {
    @Bean
    fun apiDocumentation(): Docket = Docket(SWAGGER_2)
        .groupName("My API")
        .apiInfo("My API provides a great service!")
        .build()
}
```

By default, the documentation will be generated for all endpoints declared in Spring controllers.
Swagger UI is available on `<host>/swagger-ui.html`

Please refer to [Springfox documentation](http://springfox.github.io/springfox/docs/current/#quick-start-guides) or [Baeldung tutorial](https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api) for further details.

2021-10-15 14:14 UTC, mathieulemorvan requested changes
On n'est plus très loin ! tu as tout le contenu, j'ai juste suggéré une organisation des parties

2021-10-15 14:14 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +We recommend to choose Hapi Swagger in case of NodeJS API. You can find the NPM package [here](https://www.npmjs.com/package/hapi-swagger).\
à déplacer dans la partie node

2021-10-15 14:14 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +- An active community.
j'imagine que ça s'applique à hapi swagger donc à déplacer aussi

2021-10-15 14:14 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +An example can be found here: [Petstore sample](https://petstore.swagger.io/) provided by [swagger.io](https://swagger.io/) team.
à déplacer dans la partie Swagger en-dessous

2021-10-15 14:14 UTC, mathieulemorvan commented on recipes/self-generated-documentation.md
> +- Automate the generation of your documentation.
ces deux points on l'air perdus au milieu de nulle part
peut-être qu'ils sont à mettre au début de Recipe ?

suggestion pour organiser un peu tout ça :
```md
## Recipe
To provide an efficient API documentation to your consumers, you will have to:
- Chose your documentation standard.
- Automate the generation of your documentation.

### Chose your documentation standard

We highly recommend you to choose OpenAPI standards.... (blablabla)

** Swagger example:** 
...

### Automate the generation

[ajouter ici quelques mots d'intro sur les bienfaits de la génération auto, par exemple :
In most languages and frameworks for developing web applications, libraries exist for automatically generating the Swagger description of your API.
These tools are able to list the endpoints declared in the application, and read some attached metadata to describe resources, parameters, responses...

Here are a few example with common frameworks.
[/exemple]

#### Implementation example with Node.Js
...

#### Implementation example with Java / Kotlin / Spring
...
```

2021-12-14 14:23 UTC, kevin-julien commented on recipes/self-generated-documentation.md
> +If you have a Spring application (in Java or Kotlin), you can use the [Springfox lib](https://springfox.github.io/springfox/) to:
A priori, il ne faut plus utiliser springfox mais plutôt springdoc-openapi

2022-01-03 09:04 UTC, merged