feat: add asynchronous api recipe
octo-woapi/cookbook pull request #53
Opened 2021-09-10 10:15 UTC by kevin-julien

Ajout de la recette d'une API asynchrone.

Deux cas décrit : 
- polling
- callback url

Pour le moment l'article est en français, je traduis une fois les retours sur le fond terminé.

2021-09-17 11:29 UTC, mathieulemorvan requested changes
c'est top, merci !

2021-09-17 11:29 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +Le but étant de dé-corréler le trafic http de l’api du traitement « lourd » d’un batch.
ou pars le lancement d'une tâche asynchrone, suivant ton langage (thread, coroutine...)

2021-09-17 11:29 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +    curl -X POST https://api.example.com/v1/sells/report
`reports` pour rester au pluriel

2021-09-17 11:29 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +(via l'URI renseigné dans le header [Location](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location)).
c'est une info importante, je te suggère d'enlever les parenthèse et de le mettre après l'exemple curl, comme l'explication du 202

2021-09-17 11:29 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +## Async API with polling
Recipe 1 : ...

2021-09-17 11:29 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +* Le développement supplémentaire d’un endpoint de suivi d’avancement coté serveur;
il y a une version plus simple : au lieu d'avoir un endpoint de status, tu fais un GET sur la ressource créée, et tu attends qu'elle ne soit plus en 404

quelqu'un m'a aussi parlé d'utiliser le verbe HEAD pour avoir le statut de la ressource, mais c'est un peu exotique

2021-09-17 14:53 UTC, kevin-chheang commented on recipes/asynchronous-api.md
> +Le polling est la solution la plus simple à mettre à en œuvre.\
```suggestion
Le polling est la solution la plus simple à mettre en œuvre.\
```

2021-09-17 14:53 UTC, kevin-chheang commented on recipes/asynchronous-api.md
> +Quelle est la politique à adopter ? Une première réponse serai de mettre en place une mécanique de retry avec un laps de temps entre chaque essai.
```suggestion
Quelle est la politique à adopter ? Une première réponse serait de mettre en place une mécanique de retry avec un laps de temps entre chaque essai.
```

2021-09-17 14:53 UTC, kevin-chheang commented on recipes/asynchronous-api.md
> +    curl -X POST https://api.example.com/v1/sells/report
```suggestion
    curl -X POST https://api.example.com/v1/orders/report
```
sells => orders ? on parle de commandes. A changer pour tous les exemples.

2021-09-17 14:53 UTC, kevin-chheang commented on recipes/asynchronous-api.md
> +* La solution est **utilisable seulement dans des échanges serveur à serveur**;
Pourquoi seulement utilisable entre serveurs ?
Et pas entre api et front ?

2021-09-21 11:00 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +## Async API with polling
Corrigé

2021-09-21 11:00 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +(via l'URI renseigné dans le header [Location](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location)).
Corrigé

2021-09-21 11:00 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +Le polling est la solution la plus simple à mettre à en œuvre.\
Corrigé

2021-09-21 11:00 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +Quelle est la politique à adopter ? Une première réponse serai de mettre en place une mécanique de retry avec un laps de temps entre chaque essai.
Corrigé

2021-09-21 11:01 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +    curl -X POST https://api.example.com/v1/sells/report
Merci pour l'indication :)

2021-09-21 11:04 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +* La solution est **utilisable seulement dans des échanges serveur à serveur**;
Pour de la communication serveur vers client, il faudrait se tourner vers : 
* du SSE, unidirectionnelle serveur -> client
* du websocket, bi-directionnelle

Le but de la callback url est d'indiquer une adresse avec un nom de domaine. C'est pourquoi on ne l'utilise pas avec des terminaux "client" (pc, smartphone, tablette...)

2021-09-21 11:11 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +Le but étant de dé-corréler le trafic http de l’api du traitement « lourd » d’un batch.
Ma formulation est peut être à revoir,  je veux indiquer qu'il ne faut pas que l'API exécute/déclenche la tâche lourde, le but étant de créer une rupture vis à vis du traffic. Finalement, même avec la création d'une tâche asynchrone, nous pourrions nous retrouver avec des centaines de thread crées lors d'un pique de charge. Cela pourrait mettre à mal notre app.

2021-09-21 11:18 UTC, kevin-julien commented on recipes/asynchronous-api.md
> +* Le développement supplémentaire d’un endpoint de suivi d’avancement coté serveur;
Ah ce commentaire soulève un point intéressant sur cette solution :) 
J'ai omis dans ce _recipe_ de parler de la gestion d'erreur du traitement asynchrone.

Pour moi, cette route `GET /my-ressource/status` doit être en mesure d'indiquer : 
- "OK", la ressource est créer, voici le lien 
- "KO", la ressource n'a pas été créer, voici un payload d'erreur

Avec la seule route `GET /my-ressource` comment distingues-tu un _"404, la ressource est pas crée car le traitement n'est pas fini"_ d'un _"404, la ressource est pas crée car le traitement a fini en erreur"_ ? 
Le but étant d'indiquer au client d'arrêter de solliciter le endpoint pour rien :D

2021-09-21 15:02 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +Le but étant de dé-corréler le trafic http de l’api du traitement « lourd » d’un batch.
Tu as raison, mais c'est vraiment à décorréler du design de l'API.

Tu peux par exemple avoir un traitement qui va prendre plusieurs minutes, ce qui t'oblige à exposer une API asynchrone, tout en sachant que la charge attendue sur ce traitement ne nécessite pas la mise en place d'une archi asynchrone derrière (un batch qui tourne une fois par jour pour générer un export, par exemple).

Je nuancerais juste la formulation, en remplaçant "le but étant" par quelque chsoe comme "par exemple, on peut décorréler ... quand c'est nécessaire".

2021-09-21 15:04 UTC, mathieulemorvan commented on recipes/asynchronous-api.md
> +* Le développement supplémentaire d’un endpoint de suivi d’avancement coté serveur;
ahhh oui bien vu !
eh bien ça peut carrément apparaître dans la recette
c'est presque un "don't" : si vous faites GET + 404 , vous n'avez pas de gestion d'erreur

2022-04-01 15:47 UTC, merged